version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: finance-db
    restart: always
    command:
      --innodb-buffer-pool-size=128M
      --max-connections=50
      --performance-schema=OFF
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance-api-db
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 300m

  api:
    build: .
    container_name: finance-api
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATASOURCE_URL: jdbc:mysql://db:3306/finance-api-db?allowPublicKeyRetrieval=true&useSSL=false
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: root
      TOKEN_SENHA: 222222
    deploy:
      resources:
        limits:
          memory: 512m

volumes:
  db_data:
